### ISSUE TITLE
ORTModelXXX fail -  'ORTModelForSeq2SeqLM' object has no attribute 'can_generate'

### ISSUE THREAD

**Issue by mht-sharma** [huggingface/optimum#656]
### System Info

```shell
- `optimum` version: 1.6.2.dev0
- `transformers` version: 4.26.0.dev0
- Platform: Linux-5.4.0-125-generic-x86_64-with-glibc2.17
- Python version: 3.8.15
- Huggingface_hub version: 0.11.0
- PyTorch version (GPU?): 1.13.1+cu117 (cuda availabe: True)
- Tensorflow version (GPU?): 2.10.1 (cuda availabe: False)
```

### Who can help?

@JingyaHuang 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python
model = ORTModelForSeq2SeqLM.from_pretrained("t5-small", from_transformers=True)
processor = AutoTokenizer.from_pretrained("t5-small")
onnx_translation = pipeline("translation_en_to_fr", model=model, tokenizer=processor)

result = onnx_translation("My name is Eustache")
```

**Error** - 
```bash
AttributeError: 'ORTModelForSeq2SeqLM' object has no attribute 'can_generate'
```

### Expected behavior

Should work

**Comment by mht-sharma** [comment]
The error occurs on `transformers` version: 4.26.0.dev0 but works on 4.25.1

**Comment by fxmarty** [comment]
@mht-sharma Yes this is fixed in https://github.com/huggingface/optimum/pull/651!
