### ISSUE TITLE
Does not work with Numpy 1.24

### ISSUE THREAD

**Issue by j-adamczyk** [huggingface/optimum#610]
### System Info

```shell
Python 3.9.16, Ubuntu 20.04, relevant libraries:

numpy                    1.24.0
onnx                     1.12.0
onnxruntime              1.13.1
optimum                  1.5.1
```
```


### Who can help?

@phi

### Information

- [ ] The official example scripts
- [ ] My own modified scripts
- [X] Semi-official tutorial

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I tried running [this tutorial by Philipp Schmid](https://www.philschmid.de/optimizing-transformers-with-optimum), with a pipeline:
```
from optimum.onnxruntime import ORTModelForSequenceClassification
from transformers import AutoTokenizer, pipeline

model_id = "optimum/distilbert-base-uncased-finetuned-banking77"
dataset_id = "banking77"

# load vanilla transformers and convert to onnx
model = ORTModelForSequenceClassification.from_pretrained(model_id, from_transformers=True)
tokenizer = AutoTokenizer.from_pretrained(model_id)

vanilla_clf = pipeline("text-classification", model=model, tokenizer=tokenizer)
vanilla_clf("Could you assist me in finding my lost card?")
```

Error that I got:
```
/home/jakub/.cache/pypoetry/virtualenvs/ml-coupons-cCNR6ecu-py3.9/lib/python3.9/site-packages/transformers/generation_utils.py:24: FutureWarning: Importing `GenerationMixin` from `src/transformers/generation_utils.py` is deprecated and will be removed in Transformers v5. Import as `from transformers import GenerationMixin` instead.
  warnings.warn(
/home/jakub/.cache/pypoetry/virtualenvs/ml-coupons-cCNR6ecu-py3.9/lib/python3.9/site-packages/transformers/models/distilbert/modeling_distilbert.py:217: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  mask, torch.tensor(torch.finfo(scores.dtype).min)
/home/jakub/.cache/pypoetry/virtualenvs/ml-coupons-cCNR6ecu-py3.9/lib/python3.9/site-packages/onnxruntime/transformers/io_binding_helper.py:35: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
  "tensor(bool)": numpy.bool,
Traceback (most recent call last):
  File "/home/jakub/PycharmProjects/ml-coupons/ml_sagemaker/tmp.py", line 8, in <module>
    model = ORTModelForSequenceClassification.from_pretrained(model_id, from_transformers=True)
  File "/home/jakub/.cache/pypoetry/virtualenvs/ml-coupons-cCNR6ecu-py3.9/lib/python3.9/site-packages/optimum/onnxruntime/modeling_ort.py", line 269, in from_pretrained
    return super().from_pretrained(
  File "/home/jakub/.cache/pypoetry/virtualenvs/ml-coupons-cCNR6ecu-py3.9/lib/python3.9/site-packages/optimum/modeling_base.py", line 256, in from_pretrained
    return cls._from_transformers(
  File "/home/jakub/.cache/pypoetry/virtualenvs/ml-coupons-cCNR6ecu-py3.9/lib/python3.9/site-packages/optimum/onnxruntime/modeling_ort.py", line 416, in _from_transformers
    return cls._from_pretrained(save_dir.as_posix(), **kwargs)
  File "/home/jakub/.cache/pypoetry/virtualenvs/ml-coupons-cCNR6ecu-py3.9/lib/python3.9/site-packages/optimum/onnxruntime/modeling_ort.py", line 344, in _from_pretrained
    return cls(model=model, config=config, **kwargs)
  File "/home/jakub/.cache/pypoetry/virtualenvs/ml-coupons-cCNR6ecu-py3.9/lib/python3.9/site-packages/optimum/onnxruntime/modeling_ort.py", line 849, in __init__
    self.name_to_np_type = TypeHelper.get_io_numpy_type_map(self.model) if self.use_io_binding else None
  File "/home/jakub/.cache/pypoetry/virtualenvs/ml-coupons-cCNR6ecu-py3.9/lib/python3.9/site-packages/onnxruntime/transformers/io_binding_helper.py", line 90, in get_io_numpy_type_map
    name_to_numpy_type[input.name] = TypeHelper.ort_type_to_numpy_type(input.type)
  File "/home/jakub/.cache/pypoetry/virtualenvs/ml-coupons-cCNR6ecu-py3.9/lib/python3.9/site-packages/onnxruntime/transformers/io_binding_helper.py", line 35, in ort_type_to_numpy_type
    "tensor(bool)": numpy.bool,
  File "/home/jakub/.cache/pypoetry/virtualenvs/ml-coupons-cCNR6ecu-py3.9/lib/python3.9/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool'

Process finished with exit code 1
```

This makes sense, as `numpy.bool` has been [deprecated since NumPy 1.20](https://numpy.org/doc/stable/release/1.20.0-notes.html) and [removed in NumPy 1.24](https://numpy.org/doc/stable/release/1.24.0-notes.html), in favor of regular Python `bool`. Simply changing the types in `onnxruntime/transformers/io_binding_helper.py` to `float`, `int`, `bool` etc. should fix this behavior.

This does work on NumPy 1.23.5, as expected.

### Expected behavior

Tutorial should work.

**Comment by fxmarty** [comment]
Thank you for the report! Fixed in https://github.com/huggingface/optimum/pull/612

**Comment by fxmarty** [comment]
@j-adamczyk There are multiple issues in tf2onnx, onnxruntime related to the numpy update. I would recommend to stick with `numpy==1.23` for the following few days. We will gradually fix the errors.
